#!/usr/bin/env python3

import sys

from src.user import checkOptions
from src.files import *

# --- Check args ---

checkOptions(sys.argv[1:])


# --- Retrieves all project files --- 

files = getFiles(".kt")

# Print the list of files

for file in files:
    print(f"{file}")