#!/usr/bin/env python3

import sys

from src.user import checkOptions
from src.files import *
from src.extract import *
from src.generate import *

# --- Check args ---

checkOptions(sys.argv[1:])


# --- Retrieves all project files --- 

filesPath, projectName = getFiles(".kt")

createOutputDir(projectName)

files = []

# Print the list of files
for file in filesPath:
    #file = filesPath[6]
    data = extractData(file)
    print(f"Extract: {data.fileName}{data.extension}")

    rawData = data.getRawData()
    #print(rawData)

    for i in range(len(rawData)):
        function = extractComment(rawData[i][0])

        if data.getType() == FileType.ENUM:
            extractEnum(rawData[i][1], function)
        else:
            extractFunction(rawData[i][1], function)
        data.addFunction(function)

    latexContent = generateLatex(data)
    files.append(data)

    print(latexContent)

    #writeFile(projectName, "files/" + data.getFileName() + ".tex", latexContent)


latexMain = generateLatexMain(files)
#writeFile(projectName, "main.tex", latexMain)