#!/usr/bin/env python3

import sys

from src.user import checkOptions
from src.files import *
from src.extract import *
from src.generate import *

# --- Check args ---

checkOptions(sys.argv[1:])


# --- Retrieves all project files --- 

files = getFiles(".kt")

# Print the list of files

# for file in files:
#     print(f"{file}")

print(files[6])

data = extractData(files[6])

rawData = data.getRawData()
for i in range(len(rawData)):
    function = extractComment(rawData[i][0])
    extractFunction(rawData[i][1], function)
    data.addFunction(function)

    #print(function)

#print(data)

latexContent = generateLatex(data)

print(latexContent)